name: BUILD

on:
  push:
    branches:
      - develop
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      # - name: Run lint
      #   run: |
      #     npm run lint -- --no-fix

      - name: Run tests
        run: |
          npm run test:unit

      - name: Run circular references check
        run: |
          npm run circular-check

      - name: Build
        run: |
          npm run build

      - name: Upload fluidd.zip
        uses: actions/upload-artifact@v4
        with:
          name: fluidd-${{ github.sha }}.zip
          path: ./dist

  publish-compiled:
    name: Publish to Compiled Branch
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download fluidd.zip
        uses: actions/download-artifact@v4
        with:
          name: fluidd-${{ github.sha }}.zip
          path: ./dist

      - name: Extract ZIP file
        run: unzip './dist/*.zip' -d ./dist

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to Compiled Branch
        run: |
          git fetch origin compiled
          git checkout compiled || git checkout --orphan compiled

      - name: Copy Extracted Files
        run: |
          rm -rf ./*
          cp -r ./dist/* .

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update compiled branch with build output from ${{ github.sha }}"
          git push origin compiled --force
